/// Default mapping from validator names to their compact symbol representations.
///
/// Used by both [EskemaEncoder] and [JsonEncoder] to produce short, readable output.
/// The reverse map [defaultSymbolToName] is used by decoders.
const defaultNameToSymbol = <String, String>{
  'all': '&',
  'any': '|',
  'none': '!|',
  'not': '!',
  'throwInstead': '!!',
  'withExpectation': '->',
  'when': 'when',
  'switchBy': 'switch',
  'isType': 'type',
  'isEq': '=',
  'isDeepEq': '==',
  'isGt': '>',
  'isGte': '>=',
  'isLt': '<',
  'isLte': '<=',
  'isInRange': '<>',
  'isOneOf': 'in',
  'isTrue': 'T',
  'isFalse': 'F',
  'contains': '~',
  'stringLength': 'slen',
  'stringIsOfLength': 'slen=',
  'stringContains': 's~',
  'stringMatchesPattern': 's~/',
  'isLowerCase': 's_lc',
  'isUpperCase': 's_uc',
  'isEmail': 's_mail',
  'isStringEmpty': 's0',
  'isUrl': 's_url',
  'isStrictUrl': 's_url!',
  'isUuidV4': 's_uuid',
  'isIntString': 's_int',
  'isDoubleString': 's_dbl',
  'isNumString': 's_num',
  'isBoolString': 's_bool',
  'isDate': 's_date',
  'isDateBefore': 'd<',
  'isDateAfter': 'd>',
  'isDateBetween': 'd<>',
  'isDateSameDay': 'd=',
  'isDateInPast': 'd_past',
  'isDateInFuture': 'd_fut',
  'isJsonContainer': 'j_cont',
  'isJsonObject': 'j_obj',
  'isJsonArray': 'j_arr',
  'jsonHasKeys': 'j_keys',
  'jsonArrayLength': 'j_alen',
  'jsonArrayEvery': 'j_aevery',
  'containsKey': 'm_key',
  'containsKeys': 'm_keys',
  'containsValues': 'm_vals',
  'eskema': 'eskema',
  'eskemaStrict': 'eskema!',
  'eskemaList': 'eskema[]',
  'listEach': '[]each',
};

/// Reverse mapping from compact symbols back to validator names.
///
/// Used by both [EskemaDecoder] and [JsonDecoder] to resolve symbols during decoding.
final defaultSymbolToName = defaultNameToSymbol.map((k, v) => MapEntry(v, k));
